name: Renovate
on:
  # Allows manual/automated trigger for debugging purposes
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Renovate's log level"
        required: true
        default: "info"
        type: string
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write
  pull-requests: write

env:
  LOG_LEVEL: "info"
  RENOVATE_VERSION: "42.99.0"

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Don't waste time starting Renovate if JSON is invalid
      - name: Validate Renovate JSON
        run: npx --yes --package renovate@${RENOVATE_VERSION} -- renovate-config-validator

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e23f4d9675532445118c886434f5a34292b630b4 # v46.0.2
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Use GitHub API to create commits
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL: ${{ github.event.inputs.logLevel || env.LOG_LEVEL }}
          RENOVATE_ALLOWED_COMMANDS: '["^nix .+", "^earthly .+"]'
        with:
          configurationFile: .github/renovate.json5
          token: '${{ secrets.RENOVATE_TOKEN }}'
          mount-docker-socket: true
          docker-user: root
          docker-cmd-file: .github/renovate-entrypoint.sh
